server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  client:
    # 유레카 서버 자신은 클라이언트로 등록하지 않음
    register-with-eureka: false
    # 다른 서버의 레지스트리를 가져올 필요 없음
    fetch-registry: false

  server:
    # [개발용 설정]
    # 자기 보호 모드 해제 (이게 켜져 있으면 서비스가 죽어도 목록에서 안 지워짐)
    enable-self-preservation: false
    # 죽은 서비스 체크 주기 (ms) -> 2초마다 확인해서 바로 삭제
    eviction-interval-timer-in-ms: 2000